-- Sample Data for SmartCity InsightHub
-- Rich, realistic city data across multiple wards and categories
-- Note: Embeddings will be generated by the backend application

-- ============================================
-- SAMPLE CITIZENS (Citizens, Officers, Admin)
-- Password for all users: "password123" (will be hashed by backend)
-- ============================================

INSERT INTO Citizens (name, ward, email, role, password_hash) VALUES
-- Citizens
('Rajesh Kumar', 'Ward 1', 'rajesh@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Priya Sharma', 'Ward 2', 'priya@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Amit Patel', 'Ward 3', 'amit@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Sneha Reddy', 'Ward 4', 'sneha@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Vikram Singh', 'Ward 5', 'vikram@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Anjali Menon', 'Ward 1', 'anjali@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Rohan Desai', 'Ward 2', 'rohan@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Kavita Joshi', 'Ward 3', 'kavita@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Sanjay Gupta', 'Ward 4', 'sanjay@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Divya Nair', 'Ward 5', 'divya@email.com', 'citizen', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),

-- Ward Officers
('Officer Ramesh', 'Ward 1', 'officer1@city.gov', 'officer', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Officer Sunita', 'Ward 2', 'officer2@city.gov', 'officer', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Officer Prakash', 'Ward 3', 'officer3@city.gov', 'officer', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Officer Meena', 'Ward 4', 'officer4@city.gov', 'officer', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),
('Officer Arjun', 'Ward 5', 'officer5@city.gov', 'officer', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa'),

-- Admin
('Admin User', 'All', 'admin@city.gov', 'admin', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5oDWC0h1vtFYa');

-- ============================================
-- SAMPLE COMPLAINTS (Without embeddings - backend will generate)
-- Realistic complaints across water, power, waste, roads, health
-- ============================================

-- Water-related complaints
INSERT INTO Complaints (user_id, ward, category, description, status, date) VALUES
(1, 'Ward 1', 'Water Supply', 'No water supply in my area since yesterday morning. The entire street is affected.', 'pending', NOW() - INTERVAL '2 days'),
(2, 'Ward 2', 'Water Supply', 'Water pipe burst near Park Street causing flooding. Need immediate attention.', 'in_progress', NOW() - INTERVAL '1 day'),
(3, 'Ward 3', 'Water Supply', 'Low water pressure in taps. Cannot fill even one bucket in 30 minutes.', 'pending', NOW() - INTERVAL '3 days'),
(6, 'Ward 1', 'Water Supply', 'Dirty water coming from taps. Water has brown color and bad smell.', 'pending', NOW() - INTERVAL '1 day'),
(10, 'Ward 5', 'Water Supply', 'Water pipeline leaking in front of building causing wastage and slippery road.', 'resolved', NOW() - INTERVAL '5 days'),

-- Electricity/Power complaints
(4, 'Ward 4', 'Electricity', 'Frequent power cuts in evening hours affecting work from home.', 'pending', NOW() - INTERVAL '2 days'),
(5, 'Ward 5', 'Electricity', 'Street lights not working on Main Road creating safety issues at night.', 'in_progress', NOW() - INTERVAL '1 day'),
(7, 'Ward 2', 'Electricity', 'Transformer making loud buzzing noise. Afraid it might explode.', 'pending', NOW() - INTERVAL '4 days'),
(9, 'Ward 4', 'Electricity', 'Electric pole tilted and wires hanging low. Risk of accident.', 'in_progress', NOW() - INTERVAL '2 days'),
(1, 'Ward 1', 'Electricity', 'Power outage for more than 6 hours daily. Unable to work or study.', 'pending', NOW() - INTERVAL '1 day'),

-- Garbage/Waste Management complaints
(2, 'Ward 2', 'Waste Management', 'Garbage not collected for 5 days. Foul smell and flies everywhere.', 'pending', NOW() - INTERVAL '3 days'),
(3, 'Ward 3', 'Waste Management', 'Waste bins overflowing near school. Health hazard for children.', 'resolved', NOW() - INTERVAL '7 days'),
(8, 'Ward 3', 'Waste Management', 'People dumping construction waste on the road illegally.', 'pending', NOW() - INTERVAL '2 days'),
(10, 'Ward 5', 'Waste Management', 'No dustbins in the park. Visitors throwing garbage everywhere.', 'in_progress', NOW() - INTERVAL '1 day'),
(4, 'Ward 4', 'Waste Management', 'Garbage truck comes at irregular timings. Missing collection often.', 'pending', NOW() - INTERVAL '4 days'),

-- Road and Infrastructure complaints
(5, 'Ward 5', 'Roads', 'Large pothole on highway causing accidents. Two bikes fell yesterday.', 'in_progress', NOW() - INTERVAL '2 days'),
(6, 'Ward 1', 'Roads', 'Road completely broken with deep craters. Damaging vehicle suspensions.', 'pending', NOW() - INTERVAL '3 days'),
(7, 'Ward 2', 'Roads', 'Footpath encroached by vendors. Pedestrians forced to walk on road.', 'pending', NOW() - INTERVAL '1 day'),
(9, 'Ward 4', 'Roads', 'Drainage cover missing on main road. Risk of people falling into drain.', 'in_progress', NOW() - INTERVAL '2 days'),
(1, 'Ward 1', 'Roads', 'Speed breakers not painted. Causing accidents especially at night.', 'resolved', NOW() - INTERVAL '10 days'),

-- Health and Sanitation complaints
(2, 'Ward 2', 'Health', 'Stagnant water near community center breeding mosquitoes. Dengue risk.', 'pending', NOW() - INTERVAL '3 days'),
(3, 'Ward 3', 'Health', 'Public toilet in terrible condition. Not cleaned for weeks.', 'pending', NOW() - INTERVAL '2 days'),
(4, 'Ward 4', 'Health', 'Stray dogs attacking people. Many bite incidents reported.', 'in_progress', NOW() - INTERVAL '1 day'),
(8, 'Ward 3', 'Health', 'Open sewage drain near residential area. Unbearable smell and health hazard.', 'pending', NOW() - INTERVAL '4 days'),
(10, 'Ward 5', 'Health', 'No medical dispensary in our ward. Need to travel far for basic treatment.', 'pending', NOW() - INTERVAL '5 days'),

-- Parks and Recreation complaints
(5, 'Ward 5', 'Parks', 'Park equipment broken and rusty. Dangerous for children to play.', 'pending', NOW() - INTERVAL '2 days'),
(6, 'Ward 1', 'Parks', 'Park grass not maintained. Looks like a jungle now.', 'resolved', NOW() - INTERVAL '8 days'),
(7, 'Ward 2', 'Parks', 'No drinking water facility in the park despite summer heat.', 'pending', NOW() - INTERVAL '1 day'),

-- Traffic and Parking complaints
(8, 'Ward 3', 'Traffic', 'Traffic signal not working at busy intersection. Causing jams and accidents.', 'in_progress', NOW() - INTERVAL '1 day'),
(9, 'Ward 4', 'Traffic', 'Illegal parking blocking entire street. Emergency vehicles cannot pass.', 'pending', NOW() - INTERVAL '2 days'),
(1, 'Ward 1', 'Traffic', 'No zebra crossing near school. Children crossing road unsafely.', 'pending', NOW() - INTERVAL '3 days');

-- ============================================
-- SAMPLE ANNOUNCEMENTS (Without embeddings)
-- ============================================

INSERT INTO Announcements (ward, title, body, date) VALUES
('All', 'Water Supply Maintenance', 'Water supply will be disrupted on Sunday from 6 AM to 2 PM for pipeline maintenance. Please store water in advance.', NOW() - INTERVAL '2 days'),
('Ward 1', 'New Waste Collection Schedule', 'Garbage collection timings changed to 7 AM daily. Please keep waste bins outside before 7 AM.', NOW() - INTERVAL '5 days'),
('Ward 2', 'Road Repair Work Starting', 'Main Road repair work will begin from next Monday. Expect traffic diversions for 2 weeks.', NOW() - INTERVAL '1 day'),
('All', 'Dengue Awareness Camp', 'Free dengue screening camp organized at City Hospital on Saturday. All citizens are encouraged to participate.', NOW() - INTERVAL '3 days'),
('Ward 3', 'New Park Opening', 'Modern children''s park inaugurated near Community Center. Open from 6 AM to 8 PM daily.', NOW() - INTERVAL '7 days'),
('All', 'Online Bill Payment Portal', 'Citizens can now pay water and electricity bills online through our new portal at citypay.gov.in', NOW() - INTERVAL '10 days'),
('Ward 4', 'Street Light Installation', 'New LED street lights being installed in all dark spots. Work will be completed by month end.', NOW() - INTERVAL '4 days'),
('Ward 5', 'Vaccination Drive', 'Free vaccination drive for children under 5 years at Ward Health Center from 10 AM to 5 PM daily.', NOW() - INTERVAL '6 days'),
('All', 'Citizen Grievance App', 'Download our new SmartCity app to report complaints directly from your phone. Available on Play Store.', NOW() - INTERVAL '15 days'),
('Ward 1', 'Water Quality Testing', 'Water quality testing completed. All parameters within safe limits. Report available at ward office.', NOW() - INTERVAL '8 days');

-- ============================================
-- SAMPLE SERVICES (Without embeddings)
-- ============================================

INSERT INTO Services (ward, service_name, description, status) VALUES
('Ward 1', 'Water Tanker Service', 'Emergency water supply through tanker. Call 1234 for booking. Available 24x7 during water shortage.', 'active'),
('Ward 1', 'Garbage Collection', 'Daily door-to-door garbage collection at 7 AM. Separate wet and dry waste.', 'active'),
('Ward 2', 'Street Light Repair', 'Report non-working street lights. Repair within 48 hours. Helpline: 1235', 'active'),
('Ward 2', 'Pothole Filling', 'Report potholes for immediate filling. Takes 2-3 working days. Upload photo for faster service.', 'active'),
('Ward 3', 'Health Clinic', 'Free basic health checkup and medicines. Open Mon-Sat 9 AM to 5 PM at Ward Health Center.', 'active'),
('Ward 3', 'Senior Citizen Support', 'Home visit service for senior citizens. Includes health checkup and medicine delivery.', 'active'),
('Ward 4', 'Park Maintenance', 'Regular cleaning and maintenance of ward parks. Report issues at ward office.', 'active'),
('Ward 4', 'Stray Animal Control', 'Animal birth control and vaccination program. Call 1236 to report dangerous animals.', 'active'),
('Ward 5', 'Birth Certificate', 'Issue birth certificates within 7 working days. Apply online or at ward office.', 'active'),
('Ward 5', 'Property Tax Payment', 'Pay property tax online or at ward office. Get 5% discount for advance payment.', 'active'),
('All', 'Emergency Helpline', 'Single emergency number 1911 for all city services - fire, medical, police, disaster.', 'active'),
('All', 'Public Transport', 'City bus service operates 6 AM to 11 PM. Monthly pass available at discounted rates.', 'active');

-- ============================================
-- SAMPLE REPORTS (Officers submitting reports)
-- ============================================

INSERT INTO Reports (officer_id, ward, report_text, date) VALUES
(11, 'Ward 1', 'Completed inspection of water supply complaints. Found main pipeline issue. Repair work scheduled for weekend. All affected households will be notified.', NOW() - INTERVAL '1 day'),
(12, 'Ward 2', 'Garbage collection improved after adding new trucks. Reduced average complaint resolution time from 5 days to 2 days. Citizen satisfaction increasing.', NOW() - INTERVAL '2 days'),
(13, 'Ward 3', 'Conducted health camp in slum area. Screened 150 people. Found 12 cases of waterborne diseases. Started treatment and awareness program.', NOW() - INTERVAL '3 days'),
(14, 'Ward 4', 'Traffic signal repaired at Main Road junction. Accident rate reduced by 60% in one week. Zebra crossings also repainted near schools.', NOW() - INTERVAL '1 day'),
(15, 'Ward 5', 'New park opened with modern equipment. Receiving positive feedback from citizens. Daily footfall exceeding 500 people.', NOW() - INTERVAL '4 days'),
(11, 'Ward 1', 'Monthly ward meeting conducted. Discussed top 5 recurring complaints. Action plan prepared for street light and pothole issues.', NOW() - INTERVAL '7 days'),
(12, 'Ward 2', 'Monsoon preparedness completed. Cleaned all drainage channels. Procured sandbags and pumps for emergency use.', NOW() - INTERVAL '10 days'),
(13, 'Ward 3', 'Initiated stray dog sterilization drive. Vaccinated 45 dogs in first week. Target is 200 dogs in 3 months.', NOW() - INTERVAL '5 days');

-- ============================================
-- IMPORTANT NOTE
-- ============================================
-- The embeddings for all text fields (description, report_text, body, description)
-- will be generated by the backend application using SentenceTransformers
-- when data is inserted through the API.
--
-- To generate embeddings for existing data, run the populate_embeddings.py script
-- after setting up the backend.
